security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            oauth:
                failure_path: /connect
                login_path: /connect
                check_path: /connect
                provider: fos_userbundle
                resource_owners:
                    vkontakte:           "/login/check-vkontakte"
                    google:              "/login/check-google"
                oauth_user_provider:
                    service: hwi_oauth.user.provider.fosub_bridge
            form_login:
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager
                check_path: /auth/login_check
            anonymous:    true
            logout:
                path:           /auth/logout
                target:         /

    access_control:
        - { path: ^/auth, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/skahr, roles: ROLE_USER }